id: I6B5A502B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T21:48:02+00:00'
last_modified: '2022-06-08T06:21:23.567223+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1AC242
  title: 'རྗེ་བཙུན་ཤིང་བཟའ་པཎྜི་ཏ་སྐལ་བཟང་ཆོས་ཀྱི་རྒྱལ་མཚན་དཔལ་བཟང་པོའི་གསུང་འབུམ། '
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '6974':
      image_group_id: I2PD17755
      title: ''
      total_pages: 544
      order: 1
      base_file: 6974.txt
    2BD2:
      image_group_id: I2PD17756
      title: ''
      total_pages: 566
      order: 2
      base_file: 2BD2.txt
    1B3D:
      image_group_id: I2PD17757
      title: ''
      total_pages: 482
      order: 3
      base_file: 1B3D.txt
    881B:
      image_group_id: I2PD17758
      title: ''
      total_pages: 518
      order: 4
      base_file: 881B.txt
    '3408':
      image_group_id: I2PD17759
      title: ''
      total_pages: 514
      order: 5
      base_file: 3408.txt
    825D:
      image_group_id: I2PD17760
      title: ''
      total_pages: 462
      order: 6
      base_file: 825D.txt
    9BE0:
      image_group_id: I2PD17761
      title: ''
      total_pages: 576
      order: 7
      base_file: 9BE0.txt
    3F46:
      image_group_id: I2PD17762
      title: ''
      total_pages: 548
      order: 8
      base_file: 3F46.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
